/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo.view;
import pbo.koneksi.DetailPemesanan;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import pbo.koneksi.Pemesanan;
/**
 *
 * @author riska_ti
 */
public class DetailPemesananFrame extends javax.swing.JFrame {
    private DetailPemesanan detailPemesanan = new DetailPemesanan();
    private String[] statusOptions = {"Pending", "Processing", "Completed", "Canceled"}; 

    /**
     * Creates new form DetailPemesananFrame
     */
    public DetailPemesananFrame() {
        initComponents();
        setLocationRelativeTo(null);
        initFrame();
        tampilDataDetail();
        btnHapus.setEnabled(false);
        
        cmbProduk.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) { 
            cmbProdukActionPerformed(evt); 
        }
    });
        
        tabelDetail.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                tabelDetailMouseClicked(evt);
            }
        });
        
        // Tambahkan Action Listeners ke Tombol (agar bisa dihubungkan ke metode di bawah)
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) { btnHapusActionPerformed(evt); }
        });
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) { btnKeluarActionPerformed(evt); }
        });
    }
    
    private void initFrame() {
        // Muat data ke ComboBox
        detailPemesanan.muatIdPemesanan(cmbPemesanan);
        detailPemesanan.muatDataProduk(cmbProduk);
        
        // Isi ComboBox Status
        cmbStatus.removeAllItems();
        cmbStatus.addItem("-- Pilih Status --");
        for (String status : statusOptions) {
            cmbStatus.addItem(status);
        }
        
        bersih();
      //  enableField(false);
        txtHarga.setEditable(false); // Harga Produk harus terisi otomatis dari cmbProduk
    }
    
    private void tampilDataDetail() {
    String sql = "SELECT * FROM detail_pemesanan";
    DetailPemesanan dp = new DetailPemesanan();
    dp.tampilData(tabelDetail, sql); // sesuaikan nama JTable
}


    
    private void bersih() {
        txtIdDetailPemesanan.setText(null);
        txtJumlah.setText(null);
        txtHarga.setText(null);
        cmbProduk.setSelectedIndex(0);
        cmbStatus.setSelectedIndex(0);
        txtIdDetailPemesanan.setEditable(true);
    }
    
    private void enableField(boolean status) {
        txtIdDetailPemesanan.setEditable(status);
        txtJumlah.setEditable(status);
        cmbProduk.setEnabled(status);
        cmbStatus.setEnabled(status);
        btnTambahItem.setEnabled(status);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPemesanan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbProduk = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdDetailPemesanan = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnTambahItem = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDetail = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Pemesanan");

        cmbPemesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPemesananActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Produk");

        cmbProduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Status Detail Pemesanan");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("ID Detail Pemesanan");

        jLabel5.setText("Harga Produk");

        jLabel6.setText("Jumlah Pemesanan");

        btnTambahItem.setText("Tambah Item");
        btnTambahItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahItemActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        tabelDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDetail);

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(79, 79, 79)
                                        .addComponent(cmbPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnKeluar)
                                        .addComponent(jLabel6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(btnTambahItem))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnHapus)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdDetailPemesanan)
                                    .addComponent(txtJumlah)
                                    .addComponent(txtHarga)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCetak)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addComponent(txtcari))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdDetailPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar)
                    .addComponent(btnTambahItem)
                    .addComponent(btnCetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahItemActionPerformed
        // TODO add your handling code here:
        String idPemesanan = (String) cmbPemesanan.getSelectedItem();
        String idProduk = detailPemesanan.getIdProdukFromCmb(cmbProduk);
        String hargaStr = txtHarga.getText();
        String jumlahStr = txtJumlah.getText();
        String status = (String) cmbStatus.getSelectedItem();

        // Validasi Wajib Isi
        if (idPemesanan == null || idPemesanan.equals("-- Pilih ID Pemesanan --") || idProduk == null || txtIdDetailPemesanan.getText().isEmpty() || jumlahStr.isEmpty() || status == null || status.equals("-- Pilih Status --")) {
            JOptionPane.showMessageDialog(null, "Semua field harus diisi!");
            return;
        }

        try {
            int harga = Integer.parseInt(hargaStr);
            int jumlah = Integer.parseInt(jumlahStr);
            
            detailPemesanan.simpanDetail(txtIdDetailPemesanan.getText(), idPemesanan, idProduk, harga, jumlah, status);
            
            if (detailPemesanan.validasi) {
                tampilDataDetail();
                bersih();
            }
        } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(null, "Harga dan Jumlah harus berupa angka!");
        }
    }//GEN-LAST:event_btnTambahItemActionPerformed

    private void cmbPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPemesananActionPerformed
        // TODO add your handling code here:
        tampilDataDetail();
        bersih();
        enableField(true);
    }//GEN-LAST:event_cmbPemesananActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String idDetail = txtIdDetailPemesanan.getText().trim();
    
    if (idDetail.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus terlebih dahulu!");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(null, 
        "Yakin ingin menghapus data Detail Pemesanan dengan ID " + idDetail + " ?", 
        "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    
    if (konfirmasi == JOptionPane.YES_OPTION) {
        detailPemesanan.hapusDetail(idDetail);
        tampilDataDetail();
        bersih();
        enableField(false);
        System.out.println("Data dengan ID " + idDetail + " telah dihapus!");
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tabelDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDetailMouseClicked
        // TODO add your handling code here:
        int baris = tabelDetail.getSelectedRow();
        
        if (baris != -1) {
            DefaultTableModel model = (DefaultTableModel) tabelDetail.getModel();
            
            // Mengambil data dari tabel
            String idDetail = model.getValueAt(baris, 0).toString();
            String idPesanan = model.getValueAt(baris, 1).toString();
            String produkTabel = model.getValueAt(baris, 2).toString();
            String hargaTabel = model.getValueAt(baris, 3).toString();
            String jumlahTabel = model.getValueAt(baris, 4).toString();
            String statusTabel = model.getValueAt(baris, 5).toString();

            // Memasukkan data ke komponen input
            txtIdDetailPemesanan.setText(idDetail);
            txtIdDetailPemesanan.setEditable(false);
            txtHarga.setText(hargaTabel);
            txtJumlah.setText(jumlahTabel);

            // Set ComboBox ID Pemesanan
            cmbPemesanan.setSelectedItem(idPesanan);
            
            // Set ComboBox Produk (cari berdasarkan Nama Produk)
            for (int i = 0; i < cmbProduk.getItemCount(); i++) {
                if (cmbProduk.getItemAt(i).contains(produkTabel)) {
                    cmbProduk.setSelectedIndex(i);
                    break;
                }
            }
            
            // Set ComboBox Status
            cmbStatus.setSelectedItem(statusTabel);
            
            btnTambahItem.setEnabled(false); // Mode Tambah Item dinonaktifkan
            btnHapus.setEnabled(true);
            enableField(true); // Aktifkan field untuk melihat/mengedit (meski kita hanya implementasi hapus)
        }
    }//GEN-LAST:event_tabelDetailMouseClicked

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        String keyword = txtcari.getText();
    String sql = "SELECT * FROM detail_pemesanan WHERE "
            + "ID_Detail_Pemesanan LIKE '%" + keyword + "%' "
            + "OR ID_Pemesanan LIKE '%" + keyword + "%' "
            + "OR ID_Produk LIKE '%" + keyword + "%' "
            + "OR Status_Detail_Pemesanan LIKE '%" + keyword + "%'";

    DetailPemesanan dp = new DetailPemesanan();
    dp.tampilData(tabelDetail, sql);
    }//GEN-LAST:event_txtcariKeyReleased

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
            Pemesanan p = new Pemesanan();

    p.tampilLaporan(
        "src/laporan/lap_detail_pemesanan.jrxml",
        "SELECT * FROM detail_pemesanan"
    );
    }//GEN-LAST:event_btnCetakActionPerformed

    private void cmbProdukActionPerformed(java.awt.event.ActionEvent evt) {                                            
    String selectedItem = (String) cmbProduk.getSelectedItem();
    
    // Cek apakah item yang dipilih valid (bukan "-- Pilih Produk --")
    if (selectedItem != null && !selectedItem.equals("-- Pilih Produk --")) {
        try {
            // Mengambil harga dari item yang dipilih (Harga berada di bagian akhir string)
            int harga = detailPemesanan.getHargaProdukFromCmb(cmbProduk);
            
            // Mengisi field txtHarga
            txtHarga.setText(String.valueOf(harga));
        } catch (Exception e) {
            // Jika ada masalah parsing (seharusnya tidak terjadi jika data di DB bersih)
            txtHarga.setText(""); 
        }
    } else {
        txtHarga.setText("");
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailPemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailPemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailPemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailPemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailPemesananFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambahItem;
    private javax.swing.JComboBox<String> cmbPemesanan;
    private javax.swing.JComboBox<String> cmbProduk;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDetail;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdDetailPemesanan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
