/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo.view;
import pbo.koneksi.Konsumen;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pbo.koneksi.Pemesanan;
/**
 *
 * @author riska_ti
 */
public class KonsumenFrame extends javax.swing.JFrame {
    Konsumen konsumen = new Konsumen();
    private DefaultTableModel model;

    /**
     * Creates new form KonsumenFrame
     */
    public KonsumenFrame() {
        initComponents();
        dataKolom();
        tampilData();
        bersih();
        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int baris = jTable1.rowAtPoint(evt.getPoint());
        if (baris >= 0) {
            txtIdKonsumen.setText(jTable1.getValueAt(baris, 0).toString());
            txtNamaPerusahaan.setText(jTable1.getValueAt(baris, 1).toString());
            txtAlamatPerusahaan.setText(jTable1.getValueAt(baris, 2).toString());
            txtTelpPerusahaan.setText(jTable1.getValueAt(baris, 3).toString());
            txtIdKonsumen.setEditable(false);
        }
    }
});

    }
    
    private void dataKolom(){
            model = new DefaultTableModel();
            model.addColumn("ID_Konsumen");
            model.addColumn("Nama Perusahaan");
            model.addColumn("Alamat Perusahaan");
            model.addColumn("No. Telp");
            jTable1.setModel(model);
    }
    
    private void tampilData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            Connection conn = pbo.koneksi.Koneksi.getKoneksi();
            String sql = "SELECT * FROM KONSUMEN";
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()){
                Object[] obj = new Object[4];
                obj[0] = res.getString("ID_Konsumen");
                obj[1] = res.getString("Nama_Perusahaan");
                obj[2] = res.getString("Alamat_Perusahaan");
                obj[3] = res.getString("No_telp_Perusahaan");
                
                model.addRow(obj);
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error Tampil Data:" + e.getMessage());
        }
    }
    
    private void bersih() {
        txtIdKonsumen.setText(null);
        txtNamaPerusahaan.setText(null);
        txtAlamatPerusahaan.setText(null);
        txtTelpPerusahaan.setText(null);
        txtIdKonsumen.setEditable(true);
        
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int baris = jTable1.rowAtPoint(evt.getPoint());
        
        String id = jTable1.getValueAt(baris, 0).toString().trim();
        String nama = jTable1.getValueAt(baris, 1).toString();
        String alamat = jTable1.getValueAt(baris, 2).toString();
        String telp = jTable1.getValueAt(baris, 3).toString();
        
        txtIdKonsumen.setText(id);
        txtNamaPerusahaan.setText(nama);
        txtAlamatPerusahaan.setText(alamat);
        txtTelpPerusahaan.setText(telp);
        
        txtIdKonsumen.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        txtIdKonsumen = new javax.swing.JTextField();
        txtNamaPerusahaan = new javax.swing.JTextField();
        txtAlamatPerusahaan = new javax.swing.JTextField();
        txtTelpPerusahaan = new javax.swing.JTextField();
        txtcari = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Konsumen");

        jLabel2.setText("Nama Perusahaan");

        jLabel3.setText("Alamat Perusahaan");

        jLabel4.setText("No.Telp Perusahaan");

        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Simpan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Keluar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdKonsumen)
                    .addComponent(txtNamaPerusahaan)
                    .addComponent(txtAlamatPerusahaan)
                    .addComponent(txtTelpPerusahaan))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcari, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(32, 32, 32)
                                .addComponent(jButton2)
                                .addGap(44, 44, 44)
                                .addComponent(jButton3)
                                .addGap(48, 48, 48)
                                .addComponent(jButton4)))))
                .addGap(18, 18, 18)
                .addComponent(btnCetak)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAlamatPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelpPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(btnCetak))
                .addGap(18, 18, 18)
                .addComponent(txtcari, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = pbo.koneksi.Koneksi.getKoneksi();
            String sql = "INSERT INTO konsumen VALUES (?,?,?,?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, txtIdKonsumen.getText());
            pst.setString(2, txtNamaPerusahaan.getText());
            pst.setString(3, txtAlamatPerusahaan.getText());
            pst.setString(4, txtTelpPerusahaan.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Konsumen Berhasil Disimpan");
            
            tampilData();
            bersih();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Gagal:" + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = pbo.koneksi.Koneksi.getKoneksi();
            String sql = "UPDATE konsumen SET Nama_Perusahaan=?, Alamat_Perusahaan=?, No_telp_Perusahaan=? WHERE ID_Konsumen=?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, txtNamaPerusahaan.getText());
            pst.setString(2, txtAlamatPerusahaan.getText());
            pst.setString(3, txtTelpPerusahaan.getText());
            pst.setString(4, txtIdKonsumen.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Konsumen Berhasil Diubah");
            
            tampilData();
            bersih();
            txtIdKonsumen.setEditable(true);
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Perubahan Data Gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtIdKonsumen.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data konsumen yang akan dihapus dari tabel!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin Ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try{
                Connection conn = pbo.koneksi.Koneksi.getKoneksi();
                String sql = "DELETE FROM konsumen WHERE TRIM(ID_Konsumen)=?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                
                pst.setString(1, txtIdKonsumen.getText().trim());
                int rowsAffected = pst.executeUpdate();
                
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Data Konsumen Berhasil Dihapus");
                } else {
                    JOptionPane.showMessageDialog(null, "Penghapusan Data Gagal. ID Konsumen tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                tampilData();
                bersih();
                txtIdKonsumen.setEditable(true);            
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Penghapusan Data Gagal:" + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
         String c = txtcari.getText();

    String sql = "SELECT * FROM konsumen WHERE "
               + "ID_Konsumen LIKE '%"+c+"%' "
               + "OR Nama_Perusahaan LIKE '%"+c+"%' "
               + "OR Alamat_Perusahaan LIKE '%"+c+"%' "
               + "OR No_telp_Perusahaan LIKE '%"+c+"%'";

    konsumen.tampilData(jTable1, sql);
    }//GEN-LAST:event_txtcariKeyReleased

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        Pemesanan p = new Pemesanan();

    p.tampilLaporan(
        "src/laporan/lap_konsumen.jrxml",
        "SELECT * FROM konsumen"
    );
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonsumenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonsumenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonsumenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonsumenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonsumenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonsumenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonsumenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonsumenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonsumenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAlamatPerusahaan;
    private javax.swing.JTextField txtIdKonsumen;
    private javax.swing.JTextField txtNamaPerusahaan;
    private javax.swing.JTextField txtTelpPerusahaan;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
