/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo.view;

/**
 *
 * @author riska_ti
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JMenuBar = new javax.swing.JMenuBar();
        menuMasterData = new javax.swing.JMenu();
        menuItemKaryawan = new javax.swing.JMenuItem();
        menuItemKonsumen = new javax.swing.JMenuItem();
        menuItemProduk = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuItemPemesanan = new javax.swing.JMenuItem();
        menuItemDetailPemesanan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("MANAJEMEN ADMINISTRASI PEMESANAN PADA PERUSAHAAN PERTAMBANGAN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("CV Ki Selo Redjo");

        menuMasterData.setText("Master Data");

        menuItemKaryawan.setText("Karyawan");
        menuItemKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKaryawanActionPerformed(evt);
            }
        });
        menuMasterData.add(menuItemKaryawan);

        menuItemKonsumen.setText("Konsumen");
        menuItemKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKonsumenActionPerformed(evt);
            }
        });
        menuMasterData.add(menuItemKonsumen);

        menuItemProduk.setText("Jenis Produk");
        menuItemProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdukActionPerformed(evt);
            }
        });
        menuMasterData.add(menuItemProduk);

        JMenuBar.add(menuMasterData);

        menuTransaksi.setText("Transaksi");

        menuItemPemesanan.setText("Pemesanan");
        menuItemPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPemesananActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuItemPemesanan);

        menuItemDetailPemesanan.setText("Detail Pemesanan");
        menuItemDetailPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDetailPemesananActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuItemDetailPemesanan);

        JMenuBar.add(menuTransaksi);

        setJMenuBar(JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKaryawanActionPerformed
        // TODO add your handling code here:
        KaryawanFrame kf = new KaryawanFrame();
        
        kf.setVisible(true);
    }//GEN-LAST:event_menuItemKaryawanActionPerformed

    private void menuItemKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKonsumenActionPerformed
        // TODO add your handling code here:
        KonsumenFrame kf = new KonsumenFrame();
        
        kf.setVisible(true);
    }//GEN-LAST:event_menuItemKonsumenActionPerformed

    private void menuItemProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdukActionPerformed
        // TODO add your handling code here:
        ProdukFrame pf = new ProdukFrame();
        
        pf.setVisible(true);
    }//GEN-LAST:event_menuItemProdukActionPerformed

    private void menuItemPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPemesananActionPerformed
        // TODO add your handling code here:
        PemesananFrame pf = new PemesananFrame();
        
        pf.setVisible(true);
    }//GEN-LAST:event_menuItemPemesananActionPerformed

    private void menuItemDetailPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDetailPemesananActionPerformed
        // TODO add your handling code here:
        DetailPemesananFrame dpf = new DetailPemesananFrame();
        
        dpf.setVisible(true);
    }//GEN-LAST:event_menuItemDetailPemesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem menuItemDetailPemesanan;
    private javax.swing.JMenuItem menuItemKaryawan;
    private javax.swing.JMenuItem menuItemKonsumen;
    private javax.swing.JMenuItem menuItemPemesanan;
    private javax.swing.JMenuItem menuItemProduk;
    private javax.swing.JMenu menuMasterData;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
