/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo.view;
import pbo.koneksi.Pemesanan;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author riska_ti
 */
public class PemesananFrame extends javax.swing.JFrame {
    private Pemesanan pemesanan = new Pemesanan();

    /**
     * Creates new form PemesananFrame
     */
    public PemesananFrame() {
        initComponents();
        setLocationRelativeTo(null);
        muatComboBox();
        tampilData();
        bersih();
       // enableField(false);
        
        tblPemesanan.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                tblPemesananMouseClicked(evt);
            }
        });
        
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) { btnBatalActionPerformed(evt); }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) { btnHapusActionPerformed(evt); }
        });
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) { btnUbahActionPerformed(evt); }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) { btnSimpanActionPerformed(evt); }
        });
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) { btnKeluarActionPerformed(evt); }
        });
    }
    
    private void bersih() {
        txtIdPemesanan.setText(null);
        txtTanggal.setText(null);
        jTextArea1.setText(null);
        cmbKonsumen.setSelectedIndex(0);
        cmbKaryawan.setSelectedIndex(0);
    }
    
    private void enableField(boolean status) {
        txtIdPemesanan.setEditable(status);
        txtTanggal.setEditable(status);
        jTextArea1.setEditable(status);
        cmbKonsumen.setEnabled(status);
        cmbKaryawan.setEnabled(status);
        btnSimpan.setEnabled(status);
        btnUbah.setEnabled(!status);
        btnHapus.setEnabled(!status);
    }
    
    private void muatComboBox() {
        pemesanan.muatDataKonsumen(cmbKonsumen);
        pemesanan.muatDataKaryawan(cmbKaryawan);
    }


    private void tampilData() {
        pemesanan.tampilData(tblPemesanan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdPemesanan = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbKonsumen = new javax.swing.JComboBox<>();
        cmbKaryawan = new javax.swing.JComboBox<>();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPemesanan = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Pemesanan");

        jLabel2.setText("Tanggal Pemesanan");

        jLabel3.setText("Notes");

        txtTanggal.setText("dd/MM/yyyy");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("ID Konsumen");

        jLabel5.setText("ID Karyawan");

        cmbKonsumen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbKaryawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        tblPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPemesanan);

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTanggal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(42, 42, 42)
                                        .addComponent(txtIdPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbKonsumen, 0, 122, Short.MAX_VALUE)
                                    .addComponent(cmbKaryawan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcari, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBatal)
                        .addGap(33, 33, 33)
                        .addComponent(btnHapus)
                        .addGap(36, 36, 36)
                        .addComponent(btnUbah)
                        .addGap(34, 34, 34)
                        .addComponent(btnSimpan)
                        .addGap(42, 42, 42)
                        .addComponent(btnKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCetak)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnHapus)
                    .addComponent(btnUbah)
                    .addComponent(btnSimpan)
                    .addComponent(btnKeluar)
                    .addComponent(btnCetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String idKonsumen = pemesanan.getIdFromCmb(cmbKonsumen);
        String idKaryawan = pemesanan.getIdFromCmb(cmbKaryawan);
        String id = txtIdPemesanan.getText().trim();
        String tgl = txtTanggal.getText().trim();
        String notes = jTextArea1.getText().trim(); 

        
        if (txtIdPemesanan.getText().isEmpty() || txtTanggal.getText().isEmpty() || 
        idKonsumen.isEmpty() || idKaryawan.isEmpty()) {
       // JOptionPane.showMessageDialog(null, "ID Pemesanan, Tanggal, Konsumen, dan Karyawan harus diisi!");
        return;
        }

       
        pemesanan.simpanPemesanan(id, tgl, idKonsumen, idKaryawan, notes);

      
        if (pemesanan.validasi) {
            tampilData();
            bersih();
            enableField(false);
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if (txtIdPemesanan.getText().isEmpty()) {
           // JOptionPane.showMessageDialog(null, "Pilih data yang akan diubah terlebih dahulu!");
            return;
        }
        
        String idKonsumen = pemesanan.getIdFromCmb(cmbKonsumen);
        String idKaryawan = pemesanan.getIdFromCmb(cmbKaryawan);
        
        if (idKonsumen == null || idKaryawan == null) {
            JOptionPane.showMessageDialog(null, "Konsumen atau Karyawan tidak valid!");
            return;
        }
        
        String id = txtIdPemesanan.getText();
        String tgl = txtTanggal.getText();
        String notes = jTextArea1.getText();
        
        pemesanan.ubahPemesanan(id, tgl, idKonsumen, idKaryawan, notes);
        tampilData();
        bersih();
        enableField(false);
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (txtIdPemesanan.getText().isEmpty()) {
        //    JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus terlebih dahulu!");
            return;
        }
        
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data Pemesanan ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            pemesanan.hapusPemesanan(txtIdPemesanan.getText());
            tampilData();
            bersih();
            enableField(false);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        if (btnSimpan.isEnabled() || btnUbah.isEnabled() || btnHapus.isEnabled()) {
            bersih();
            enableField(false);
        } else {
            enableField(true); 
            bersih();
            txtIdPemesanan.requestFocus();
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        String c = txtcari.getText();

    String sql = "SELECT * FROM pemesanan "
               + "WHERE id_pemesanan LIKE '%" + c + "%' "
               + "OR id_konsumen LIKE '%" + c + "%' "
               + "OR id_karyawan LIKE '%" + c + "%'";

    pemesanan.tampilData(tblPemesanan, sql);
    }//GEN-LAST:event_txtcariKeyReleased

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        Pemesanan p = new Pemesanan();

    p.tampilLaporan(
        "src/laporan/lap_pemesanan.jrxml",
        "SELECT * FROM pemesanan"
    );
    }//GEN-LAST:event_btnCetakActionPerformed

    
    private void tblPemesananMouseClicked(java.awt.event.MouseEvent evt) {                                   
        int baris = tblPemesanan.getSelectedRow();
        
        if (baris != -1) {
            enableField(true);
            txtIdPemesanan.setEditable(false);
            
            DefaultTableModel model = (DefaultTableModel) tblPemesanan.getModel();
            
            txtIdPemesanan.setText(model.getValueAt(baris, 0).toString());
            txtTanggal.setText(model.getValueAt(baris, 1).toString());
            jTextArea1.setText(model.getValueAt(baris, 4).toString());
            
            // Set ComboBox berdasarkan Nama yang ditampilkan di tabel
            String namaKonsumenTabel = model.getValueAt(baris, 2).toString();
            String namaKaryawanTabel = model.getValueAt(baris, 3).toString();

            // Mencari item di ComboBox yang mengandung Nama yang sesuai
            for (int i = 0; i < cmbKonsumen.getItemCount(); i++) {
                if (cmbKonsumen.getItemAt(i).contains(namaKonsumenTabel)) {
                    cmbKonsumen.setSelectedIndex(i);
                    break;
                }
            }

            for (int i = 0; i < cmbKaryawan.getItemCount(); i++) {
                if (cmbKaryawan.getItemAt(i).contains(namaKaryawanTabel)) {
                    cmbKaryawan.setSelectedIndex(i);
                    break;
                }
            }
            
            btnSimpan.setEnabled(false);
            btnUbah.setEnabled(true);
            btnHapus.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbKaryawan;
    private javax.swing.JComboBox<String> cmbKonsumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblPemesanan;
    private javax.swing.JTextField txtIdPemesanan;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
